name: Check branch fast-forward-ness

on:
  pull_request:
    types: [ review_requested, synchronize ]

jobs:
  check-fast-forward-ness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ViRGiL175/check-branch-fast-forward-ness@main
